services:

  api:
    build: pist-back
    ports:
      - 8000:8000
    depends_on:
      - db
  
  ddnsd:
    build: route53-ddns
    restart: always 

  ui:
    build: pist-front


  
  db:
    image: postgres:16
    container_name: pist-db
    restart: always
    environment:
      POSTGRES_USER: pistorius_user
      POSTGRES_PASSWORD: Pistorius1234
      POSTGRES_DB: pistorius
    ports:
      - "5432:5432"
    volumes:
      - pist-db-data:/var/lib/postgresql/data

  proxy:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/nginx/html/:/usr/share/nginx/html/:ro
    depends_on:
      - api
      - ui


volumes:
  pist-db-data: {}


