events {}

http {
    server {
        listen 80;
        server_name trou.pistoriusies.co.za;

        location / {
            proxy_pass http://ui:3000;
        }

    }
    server {
        listen 80 default_server;
        listen [::]:80 default_server;

        server_name localhost 192.168.1.92 pistoriusies.co.za;

        location / {
            root   /usr/share/nginx/html;
            index  7-Nov.html;
        }

        location /api/ {
            proxy_pass http://api:8000;
        }
    }
}