version = 5.4.0
archive_dir = /etc/letsencrypt/archive/pistoriusies.co.za
cert = /etc/letsencrypt/live/pistoriusies.co.za/cert.pem
privkey = /etc/letsencrypt/live/pistoriusies.co.za/privkey.pem
chain = /etc/letsencrypt/live/pistoriusies.co.za/chain.pem
fullchain = /etc/letsencrypt/live/pistoriusies.co.za/fullchain.pem
[renewalparams]
account = ad1adff33f6e859c6e406a06b5336767
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
pistoriusies.co.za = /var/www/certbot
